name: Pytest

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r backend/requirements.pip

      - name: Unit tests
        run:
          python -m pytest -m backénd/test/test_userController.py
